### ISSUE TITLE
Subtype jar file missing

### ISSUE THREAD

**Issue by opconWizard** [SMATechnologies/opcon-agentless-bolt#1]
I have downloaded this repo and cannot locate the subtype .jar file, did I overlook something?

**Comment by oeil** [comment]
You don't need to download the repo. You can find it (.jar file) under the github repository release tab here : 
- https://github.com/SMATechnologies/opcon-agentless-bolt/releases

Each time a stable version ready we create a release and associated tag, so you can always download a stable version.

**Comment by opconWizard** [comment]
Thanks, I overlooked that.  I was confused because the .jar is available in the Azure Storage connector repo.
